Cleanup and exit if cannot download valid connection info.
rancher/system-agent pull request #151
Opened 2024-01-04 20:51 UTC by vwbusguy

This PR fixes an issue where if maximum retries are met attempting to download the rancher2_connection_info.json, the script continues with invalid data in that file causing the rancher-system-agent to fail to start.  This change cleans up the errant json file and exits the installer instead of continuing to setup a service doomed for failure.

Ref. SUSE Support case #01054437

2024-01-04 20:54 UTC, vwbusguy commented
Addresses and possibly fixes #145

2024-01-10 21:40 UTC, jakefhyde requested changes
Thank you for opening this PR. Overall the proposed change seems like a positive to me, and I don't see any immediate downsides.

2024-01-13 00:12 UTC, jakefhyde approved these changes
Approved, pending review by @Oats87

2024-01-30 18:47 UTC, Oats87 approved these changes

2024-02-02 16:53 UTC, merged